# raw data for the title abbreviation table

df_key_street <- read.table(text = 'title abbreviation type
ALLEY ALY ST
AVENUE AVE ST
BEND BND OTHER
BOULEVARD BLVD ST
BYPASS BYP ST
CIRCLE CIR ST
DRIVE DR ST
FLOOR FL OTHER
FORT FT OTHER
HIGHWAY HWY ST
HIGHWAY HW ST
JUNCTION JNCT ST
JUNCTION JCT ST
LAKE LK OTHER                    
LANE LN ST
PARKWAY PKWY ST
PLACE PL ST
POINT PT OTHER
ROAD RD ST
SUITE STE OTHER
TERRACE TERR ST
TERRACE TER ST
TRACE TRCE ST
TURNPIKE TPKE ST
TURNPIKE TRNPK ST
VIEW VW OTHER
WAY WY ST
FIRST 1ST NUM
SECOND 2ND NUM
THIRD 3RD NUM
FOURTH 4TH NUM
FIFTH 5TH NUM
SIXTH 6TH NUM
SEVENTH 7TH NUM
EIGTH 8TH NUM
NINTH 9TH NUM
TENTH 10TH NUM
ELEVENTH 11TH NUM
TWELFTH 12TH NUM
THIRTEENTH 13TH NUM
FOURTEENTH 14TH NUM
FIFTHTEENTH 15TH NUM
SIXTHTEENTH 16TH NUM
SEVENTEENTH 17TH NUM
EIGTHTEENTH 18TH NUM
NINETEENTH 19TH NUM
TWENTIETH 20TH NUM
ONE 1 NUM
EAST E DIR
WEST W DIR
NORTH N DIR
SOUTH S DIR
SOUTHWEST SW DIR
SOUTHEAST SE DIR
NORTHEAST NE DIR
NORTHWEST NW DIR', 
header = TRUE, stringsAsFactors = FALSE)

# to update:
# devtools::use_data(df_key_street, overwrite = TRUE)

# INTERSTATE I

# STREET STR
# \\1SAINT ([0-9]+\\s+)ST 
# \\1STREET ([A-Z]+\\s+)ST

#STREET ST
#SAINT ([0-9]+\\s+)ST

# https://pe.usps.com/text/pub28/28apc_002.htm
# 








